### PR TITLE
Private-Event project

### PR DESCRIPTION
**Pull request by belsman**
##  In this iteration, we created a project (Private-Event). Users log in and invite other registered Users to private events. Specifically, we implemented the following features:

- Sign Up and Sign In functionality
- Events creation and Adding Users to Events
- Listing past and future Events
- Rspec for testing models
- Access Restriction via **session** hash

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 

- Good job getting the basic app flow working here!

## However, there are some changes required 👀 🧰 🔨 🔧 

- [x] When I try to login using a username that is not registered in the database, I get the following error. Please fix it:

image

- [x] There is no way to register a new user. Please add some way for a new user to be registered so the app is usable. I was able to further test your app by manually creating a User through `rails c`, but you should still add a sign-up section.

- [ ] I'm able to attend my own created events, as well as invite myself an infinite amount of times. Please fix this so that the event can only be attended once by any user other than the creator:

image

- [x] The homepage doesn't even list the event I just created. This happened because I was able to create an event with a `NULL` date. Please fix your app so the user is not allowed to create events with empty dates.

image

**[OPTIONAL]**

- [ ] Add an option to allow the user to un-attend an event.

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: :stop_sign: 

**HELLO @belsman AND @voscarmv  YOU HAVE DONE A GOOD JOB SO FAR. EVERYTHING IS ALMOST WORKING IN YOUR APP IT JUST NEED SOME FEW IMPROVEMENTS.** :arrow_down: 

- [ ] I'm able to attend my own created events, as well as invite myself an infinite amount of times. Please fix this so that the event can only be attended once by any user other than the creator:
(just like described above by the previous TSE, kindly fix this)

### if you have any question kindly reach me son slack @peterrobert

### HAPPY CODING :computer:

**Comment by Abhigyan001** [comment]
Issue mentioned by TSE is fixed (No infinite invitation) which can be verified from the recorded video:

https://drive.google.com/file/d/19Ta8E_VDFv7r6shGMKQVBoeRT76KMOAs/view?usp=sharing

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
